name: Local Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy script from project directory
        run: |
          cd ~/PYTHON/count
          bash deploy.sh
