name: Local Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run REAL deploy script
        working-directory: /home/dani/PYTHON/count
        run: |
          bash deploy.sh
